[package]
name = "typesift_macros"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["Serhii Potapov <blake131313@gmail.com>"]
license = "MIT"
description = "Implementation detail of the typesift crate: the #[derive(TypeSift)] macro"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits", "full"] }

[lib]
proc-macro = true
