[package]
name = "typesift_test_suite"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
typesift = { path = "../typesift", features = [
    "chrono",
    "indexmap",
    "rust_decimal",
    "smallvec",
    "time",
    "uuid",
] }

chrono = "0.4"
indexmap = "2"
rust_decimal = "1"
smallvec = "1"
time = "0.3"
uuid = "1"
