[package]
name = "typesift_test_suite"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
typesift = { path = "../typesift", features = [
    "bytes",
    "chrono",
    "enum-map",
    "http",
    "indexmap",
    "rust_decimal",
    "serde_json",
    "smallvec",
    "time",
    "url",
    "uuid",
] }

bytes = "1"
chrono = "0.4"
enum-map = "3"
http = "1"
indexmap = "2"
rust_decimal = "1"
serde_json = "1"
smallvec = "1"
time = "0.3"
url = "2"
uuid = "1"
